"""
dq_checks.py — Ecommerce Orders Pipeline Data Quality Validation
Generated by Ved · Mu Sigma Data Engineering Skill
DQ threshold: 90% — pipeline halts if score falls below this.
"""
import csv
import os
import sys

DQ_THRESHOLD = float(os.environ.get("DQ_THRESHOLD", "90"))


def check_nulls(rows, col, max_pct=5.0):
    null_count = sum(1 for r in rows if r.get(col, "") in ("", "None", "null"))
    pct = null_count / len(rows) * 100 if rows else 0
    status = "PASS" if pct <= max_pct else "FAIL"
    return {
        "check": f"null_rate_{col}",
        "status": status,
        "detail": f"{pct:.1f}% nulls (threshold {max_pct}%)",
    }


def check_duplicates(rows, key_col, max_pct=1.0):
    ids = [r.get(key_col, "") for r in rows]
    dup_count = len(ids) - len(set(ids))
    pct = dup_count / len(rows) * 100 if rows else 0
    status = "PASS" if pct <= max_pct else "FAIL"
    return {
        "check": f"duplicate_{key_col}",
        "status": status,
        "detail": f"{dup_count} dupes ({pct:.1f}%)",
    }


def run_checks(data_path: str) -> dict:
    if not os.path.exists(data_path):
        print(f"[DQ] No data found at {data_path} — skipping checks")
        return {"score": 100, "pass": 0, "warn": 0, "fail": 0, "results": []}

    with open(data_path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return {"score": 100, "pass": 0, "warn": 0, "fail": 0, "results": []}

    results = []
    cols = list(rows[0].keys())

    for col in cols[:5]:
        results.append(check_nulls(rows, col, max_pct=5.0))

    if cols:
        results.append(check_duplicates(rows, cols[0], max_pct=1.0))

    pass_count = sum(1 for r in results if r["status"] == "PASS")
    fail_count = sum(1 for r in results if r["status"] == "FAIL")
    score = round(pass_count / len(results) * 100, 1) if results else 100

    return {"score": score, "pass": pass_count, "warn": 0, "fail": fail_count, "results": results}


if __name__ == "__main__":
    data_path = "data/transformed_data.csv"
    result = run_checks(data_path)
    print(f"\n[DQ] Score: {result['score']}% | PASS: {result['pass']} | FAIL: {result['fail']}")
    for r in result["results"]:
        print(f"  [{r['status']}] {r['check']} — {r['detail']}")
    if result["score"] < DQ_THRESHOLD:
        print(f"\n[DQ] FAIL — Score {result['score']}% < threshold {DQ_THRESHOLD}%")
        sys.exit(1)
    else:
        print(f"\n[DQ] PASS — Score {result['score']}% meets threshold {DQ_THRESHOLD}%")
        sys.exit(0)
