"""
transform.py — Ecommerce Orders Pipeline Silver Layer Transforms
Generated by Ved · Mu Sigma Data Engineering Skill
"""
import csv
import hashlib


def sha256(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest() if value else ""


def normalise_columns(row: dict) -> dict:
    return {k.strip().lower().replace(" ", "_"): v for k, v in row.items()}


def fill_nulls(row: dict, rules: dict) -> dict:
    for col, default in rules.items():
        if col in row and row[col] in ("", "None", "null", "NULL"):
            row[col] = default
    return row


def mask_pii(row: dict, pii_cols: list) -> dict:
    for col in pii_cols:
        if col in row:
            row[col + "_hashed"] = sha256(row.pop(col))
    return row


def transform(
    source_path: str,
    dest_path: str,
    pii_cols: list = None,
    null_rules: dict = None,
) -> int:
    pii_cols = pii_cols or []
    null_rules = null_rules or {}
    with open(source_path, newline="") as src_file:
        rows = list(csv.DictReader(src_file))
    seen = set()
    silver = []
    for r in rows:
        r = normalise_columns(r)
        r = fill_nulls(r, null_rules)
        r = mask_pii(r, pii_cols)
        key = tuple(r.values())
        if key not in seen:
            seen.add(key)
            silver.append(r)
    if silver:
        with open(dest_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=silver[0].keys())
            writer.writeheader()
            writer.writerows(silver)
    print(f"[TRANSFORM] {len(rows)} -> {len(silver)} rows written to {dest_path}")
    return len(silver)


if __name__ == "__main__":
    transform(
        "data/raw_data.csv",
        "data/transformed_data.csv",
        pii_cols=[],
        null_rules={},
    )
